## Server Properties
server:
   port: 8081

spring:
 cloud:
   vault:
        url: http://vault:8200
        token: 00000000-0000-0000-0000-000000000000
        scheme: http
        host: vault
        port: 8200
        kv:
         enabled: true
         backend: secret
         application-name: hospitalmanagementsystem
   config:
      import: 
        - vault://secret/hospitalmanagementsystem/test
   datasource:
      username: ${dbusername}
      password: ${dbpassword}
      url: ${dbjdbcurl}
   redis:
      host: redis
      port: 6379
   cache:
      redis:
        cache-null-values: false
        time-to-live: 6000000
        

api:
   username: ${api_username}
   password: ${api_password}
   secretKey: ${secret_key}

management:
   endpoints:
       web:
         exposure:
             include: '*'