spring:
  application:
    name: hospitalmanagementsystem
  profiles:
    active: '@activatedProfile@' 
  cloud:
      vault:
        url: http://localhost:8200
        token: s.q5cEyiJoNoHdwoULn3dr2aeA
        scheme: http
        host: localhost
        port: 8200
        kv:
         enabled: true
         backend: vaultdemo
         application-name: hospitalmanagementsystem
  config:
     import: vault://hospitalmanagementsystem
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl