spring:
  datasource:
    url: 'jdbc:mysql://localhost:3306/usersvc'
    username: root
    password: Abirami@01052020
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl