## Server Properties
server:
   port: 8090

spring:
   config:
      import: vault://hospitalmanagementsystem/prod
   datasource:
      username: ${dbusername}
      password: ${dbpassword}
      url: ${dbjdbcurl}

api:
   username: ${api_username}
   password: ${api_password}
   secretKey: ${secret_key}