## Server Properties
server:
   port: 8083

spring:
   cloud:
      consul:
        config:
           format: yaml
   config:
      import: 
        - vault://secret/hospitalmanagementsystem/test
        - consul:localhost:8500
   datasource:
      username: ${dbusername}
      password: ${dbpassword}
      url: ${dbjdbcurl}
   redis:
      host: 127.0.0.1
      port: 6379
   cache:
      redis:
        cache-null-values: false
        time-to-live: 6000000
        

api:
   username: ${api_username}
   password: ${api_password}
   secretKey: ${secret_key}
   userServiceAccessToken: ${userServiceAccessToken}
   patientServiceAccessToken: ${patientServiceAccessToken} 