spring:
  application:
    name: hospitalmanagementsystem
  profiles:
    active: '@activatedProfile@' 
  cloud:
      vault:
        url: http://vault:8200
        token: 00000000-0000-0000-0000-000000000000
        scheme: http
        host: vault
        port: 8200
        kv:
         enabled: true
         backend: secret
         application-name: hospitalmanagementsystem
  config:
     import: 
       - vault://secret/hospitalmanagementsystem/test
  datasource:
      username: ${dbusername}
      password: ${dbpassword}
      url: ${dbjdbcurl}
  jpa:
    properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl