## Server Properties
server:
   port: 8083

spring:
 application:
    name: vital-sign-service
 cloud:
   consul:
         host: localhost
         port: 8500
         config:
           enabled: false
         discovery:
           healthCheckInterval: 15s
           instance-id: vital-sign-service
         load-balancer:
           ribbon:
             enabled: false
   vault:
        url: http://localhost:8200
        token: 00000000-0000-0000-0000-000000000000
        scheme: http
        host: localhost
        port: 8200
        kv:
         enabled: true
         backend: secret
         application-name: hospitalmanagementsystem
   config:
      import: 
        - vault://secret/hospitalmanagementsystem/test
   datasource:
      username: ${dbusername}
      password: ${dbpassword}
      url: ${dbjdbcurl}      

api:
   username: ${api_username}
   password: ${api_password}
   secretKey: ${secret_key}
   userServiceAccessToken: ${userServiceAccessToken}
   patientServiceAccessToken: ${patientServiceAccessToken}


management:
   endpoints:
       web:
         exposure:
             include: '*'