spring:
  application:
    name: hospitalmanagementsystem
  profiles:
    active: '@activatedProfile@' 
  cloud:
      consul:
        config:
           format: yaml
      vault:
        url: http://localhost:8200
        token: 00000000-0000-0000-0000-000000000000
        scheme: http
        host: localhost
        port: 8200
        kv:
         enabled: true
         backend: secret
         application-name: hospitalmanagementsystem
  config:
     import: 
       - vault://secret/hospitalmanagementsystem
       - consul:localhost:8500
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl