## Server Properties
server:
   port: 8082

spring:
   config:
      import: vault://vaultdemo/hospitalmanagementsystem/stage
   datasource:
      username: ${dbusername}
      password: ${dbpassword}
      url: ${dbjdbcurl}